apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cassandra
    location: oer
  name: cassandra-oer
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cassandra
      location: oer
  serviceName: cassandra-headless-oer
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: cassandra
        location: oer
    spec:
      containers:
        - env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SEEDS
              value: cassandra-zh-0.cassandra-headless-zh.cassandra.svc,cassandra-oer-0.cassandra-headless-oer.cassandra.svc
            - name: CASSANDRA_CLUSTER_NAME
              value: K8Demo
            - name: CASSANDRA_DC
              value: DC1-OER-K8Demo
            - name: CASSANDRA_RACK
              value: Rack1-K8Demo
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: cassandra-password
                  name: cassandra
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: 'quay.io/sychen/cassandra:3.11'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - /opt/scripts/pre-stop.sh
          name: cassandra
          ports:
            - containerPort: 7000
              name: intra-node
              protocol: TCP
            - containerPort: 7001
              name: tls-intra-node
              protocol: TCP
            - containerPort: 7199
              name: jmx
              protocol: TCP
            - containerPort: 9042
              name: cql
              protocol: TCP
            - containerPort: 9160
              name: thrift
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - /ready-probe.sh
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
        - image: 'criteord/cassandra_exporter:2.0.4'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: metrics
            timeoutSeconds: 1
          name: metrics
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 5555
              name: jmx
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 45
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          app: cassandra
          location: oer
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      status:
        phase: Pending
