apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cassandra
  name: cassandra
spec:
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: cql
  - name: thrift
    port: 9160
    protocol: TCP
    targetPort: thrift
  selector:
    app: cassandra
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
