apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cassandra
    location: zh
  name: cassandra-headless-zh
spec:
  clusterIP: None
  ports:
  - name: intra-node
    port: 7000
    protocol: TCP
    targetPort: intra-node
  - name: tls-intra-node
    port: 7001
    protocol: TCP
    targetPort: tls-intra-node
  - name: jmx
    port: 7199
    protocol: TCP
    targetPort: jmx
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: cql
  - name: thrift
    port: 9160
    protocol: TCP
    targetPort: thrift
  publishNotReadyAddresses: true
  selector:
    app: cassandra
    location: zh
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
